catalog:
  tag: "ffe1df"
orders_db:
  tag: "73e2b2"
catalog_db:
  tag: "ffe1df"
cart:
  tag: "69e73f"
cart_dynamodb:
  tag: "69e73f"
orders:
  tag: "73e2b2"
orders_db_rabbitmq:
  tag: "73e2b2"
checkout:
  tag: "b45290"
checkout_db:
  tag: "b45290"
assets:
  tag: "4c2902"
ui:
  tag: "9eb2be"
