catalog:
  tag: "137b20"
orders_db:
  tag: "282748"
catalog_db:
  tag: "137b20"
cart:
  tag: "69e73f"
cart_dynamodb:
  tag: "69e73f"
orders:
  tag: "282748"
orders_db_rabbitmq:
  tag: "282748"
checkout:
  tag: "b45290"
checkout_db:
  tag: "b45290"
assets:
  tag: "4c2902"
ui:
  tag: "7d7a91"
